version: '3'

services:
  my_postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: my_password
    ports:
      - "5432:5432"

  my_flask_app:
    build: ./api
    volumes:
      - ./api:/app
    ports:
      - "5000:5000"
    depends_on:
      - my_postgres
